import sys
import os
import io
import base64
import time
import subprocess
import tempfile
from pathlib import Path
import numpy as np
import trimesh
from fastapi import FastAPI, UploadFile, File, Form, HTTPException
from fastapi.staticfiles import StaticFiles
from fastapi.responses import JSONResponse
import uvicorn

ROOT = Path(__file__).resolve().parents[1]

app = FastAPI(title="SDF Dual Contouring Studio API")

STATIC_DIR = ROOT / "webapp" / "static"
if not STATIC_DIR.exists():
    STATIC_DIR.mkdir(parents=True, exist_ok=True)

@app.post("/api/extract")
async def extract_mesh(
    file: UploadFile = File(None),
    res: int = Form(64),
    backend: str = Form("cuda-sparse-mvdc"),
    brick_size: int = Form(8),
    scale_factor: float = Form(0.85),
    close_holes: bool = Form(False),
    remove_floaters: bool = Form(False)
):
    try:
        if file is None or not hasattr(file, "read"):
            default_path = ROOT / "test_input.glb"
            if not default_path.exists():
                default_path = ROOT.parent / "test_input.glb"
            mesh = trimesh.load(str(default_path), force='mesh')
        else:
            content = await file.read()
            file_obj = io.BytesIO(content)
            mesh = trimesh.load(file_obj, file_type='glb', force='mesh')

        res = max(16, min(2048, int(res)))
        brick_size = 16 if brick_size == 16 else 8

        binary_path = ROOT / "build" / "dc_cli"
        if not binary_path.exists():
            raise RuntimeError(f"dc_cli binary not found at {binary_path}. Please run make dc_cli.")

        t0 = time.time()
        with tempfile.TemporaryDirectory() as tmpdir:
            temp_in = os.path.join(tmpdir, "in.obj")
            temp_out = os.path.join(tmpdir, "out.obj")

            mesh.export(temp_in, file_type='obj')

            cmd = [
                str(binary_path),
                "-i", temp_in,
                "-o", temp_out,
                "-g", str(res),
                "-b", backend,
                "--brick-size", str(brick_size)
            ]
            if close_holes:
                cmd.append("--close-holes")
            if remove_floaters:
                cmd.append("--remove-floaters")

            proc = subprocess.run(cmd, capture_output=True, text=True, check=True)
            total_ms = (time.time() - t0) * 1000.0

            if not os.path.exists(temp_out):
                raise RuntimeError("Remeshed file was not generated by dc_cli")

            out_mesh = trimesh.load(temp_out, file_type='obj', force='mesh')

        if len(out_mesh.vertices) == 0 or len(out_mesh.faces) == 0:
            raise ValueError("No zero-crossing surface found in the specified grid resolution.")

        V_out = np.array(out_mesh.vertices, dtype=np.float32).reshape(-1, 3)
        F_out = np.array(out_mesh.faces, dtype=np.int32).reshape(-1, 3)
        result_mesh = trimesh.Trimesh(
            vertices=V_out,
            faces=F_out,
            process=False
        )
        glb_bytes = result_mesh.export(file_type='glb')
        glb_base64 = base64.b64encode(glb_bytes).decode('utf-8')

        return JSONResponse({
            "success": True,
            "glb_base64": glb_base64,
            "stats": {
                "face_emission_ms": round(stats.face_emission_ms, 3),
                "download_ms": round(stats.download_ms, 3),
                "total_bricks": stats.total_bricks,
                "active_bricks": stats.active_bricks,
                "active_cells": stats.active_cells,
                "total_cells": stats.total_cells,
                "ambiguous_cells": getattr(stats, "ambiguous_cells", 0),
                "multi_vertex_cells": getattr(stats, "multi_vertex_cells", 0),
                "split_rejection_count": getattr(stats, "split_rejection_count", 0),
                "res": res
            }
        })
    except Exception as e:
        return JSONResponse(status_code=500, content={"success": False, "error": str(e)})

@app.get("/api/default_glb")
async def get_default_glb():
    default_path = ROOT / "test_input.glb"
    if not default_path.exists():
        default_path = ROOT.parent / "test_input.glb"
    if not default_path.exists():
        raise HTTPException(status_code=404, detail="test_input.glb not found")
    with open(default_path, "rb") as f:
        data = f.read()
    return JSONResponse({
        "success": True,
        "filename": "test_input.glb",
        "glb_base64": base64.b64encode(data).decode('utf-8')
    })

app.mount("/", StaticFiles(directory=str(STATIC_DIR), html=True), name="static")

if __name__ == "__main__":
    uvicorn.run("server:app", host="0.0.0.0", port=8080, reload=False)
